resources:
  - pg.yaml
  - pgpv.yaml
  - pgpvc.yaml

commonLabels:
  environment: dev

namespace: {{  $sys.id }}

configMapGenerator:
  - name: pg-config
    literals:
      - defaultPassword=admin
      - pgDefaultUsername={{ $var.wrongname }}
      - pgDefaultPassword={{ $var.password }}